/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view.adm;

import javax.swing.JOptionPane;
import mvc.controller.Login;
import mvc.model.Calendario;
import mvc.model.Taxa;
import mvc.view.TelaLogin;
import mvc.view.adm.cdb.TelaCDBConsultarEditar;
import mvc.view.adm.clientes.TelaEditarClientes;
import mvc.view.adm.corrente.TelaConsultarAlterarCorrente;
import mvc.view.adm.corrente.TelaMovimentacoes;
import mvc.view.adm.fundos.TelaFundoConsultarEditar;
import mvc.view.adm.poupanca.TelaConsultarAlterarPoupanca;
import mvc.view.adm.poupanca.TelaConsultarDepositos;

/**
 *
 * @author leonardo
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private Login logado = new Login();
    private Calendario calendario = new Calendario();
    private Taxa taxas = new Taxa();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuAvancaTempo = new javax.swing.JMenuItem();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuClientesEditar = new javax.swing.JMenuItem();
        menuCorrente = new javax.swing.JMenu();
        menuCorrenteEditar = new javax.swing.JMenuItem();
        menuCCMovimentacoes = new javax.swing.JMenuItem();
        menuPoupanca = new javax.swing.JMenu();
        menuPoupancaAlterar = new javax.swing.JMenuItem();
        menuCPConsultarDepositos = new javax.swing.JMenuItem();
        menuCDB = new javax.swing.JMenu();
        menuCDBEditar = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuFundosEditar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco de investimentos -  " + logado.getLogado().getNome() + " - " + calendario.getDataFormatada());

        menuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_text.png"))); // NOI18N
        menuArquivo.setText("Arquivo");

        menuAvancaTempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time_add.png"))); // NOI18N
        menuAvancaTempo.setText("Avançar data");
        menuAvancaTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAvancaTempoActionPerformed(evt);
            }
        });
        menuArquivo.add(menuAvancaTempo);

        menuArquivoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disconnect.png"))); // NOI18N
        menuArquivoSair.setText("Sair");
        menuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuArquivoSair);

        jMenuBar1.add(menuArquivo);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        menuClientes.setText("Clientes");

        menuClientesEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_edit.png"))); // NOI18N
        menuClientesEditar.setText("Consultar / Editar");
        menuClientesEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesEditarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesEditar);

        jMenuBar1.add(menuClientes);

        menuCorrente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money.png"))); // NOI18N
        menuCorrente.setText("Contas Corrente");

        menuCorrenteEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table_edit.png"))); // NOI18N
        menuCorrenteEditar.setText("Consultar / Editar");
        menuCorrenteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCorrenteEditarActionPerformed(evt);
            }
        });
        menuCorrente.add(menuCorrenteEditar);

        menuCCMovimentacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        menuCCMovimentacoes.setText("Movimentações");
        menuCCMovimentacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCCMovimentacoesActionPerformed(evt);
            }
        });
        menuCorrente.add(menuCCMovimentacoes);

        jMenuBar1.add(menuCorrente);

        menuPoupanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N
        menuPoupanca.setText("Contas Poupança");

        menuPoupancaAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table_edit.png"))); // NOI18N
        menuPoupancaAlterar.setText("Consultar / Editar");
        menuPoupancaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPoupancaAlterarActionPerformed(evt);
            }
        });
        menuPoupanca.add(menuPoupancaAlterar);

        menuCPConsultarDepositos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table.png"))); // NOI18N
        menuCPConsultarDepositos.setText("Consultar depósitos");
        menuCPConsultarDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCPConsultarDepositosActionPerformed(evt);
            }
        });
        menuPoupanca.add(menuCPConsultarDepositos);

        jMenuBar1.add(menuPoupanca);

        menuCDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N
        menuCDB.setText("CDB's");

        menuCDBEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table_edit.png"))); // NOI18N
        menuCDBEditar.setText("Consultar / Editar");
        menuCDBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCDBEditarActionPerformed(evt);
            }
        });
        menuCDB.add(menuCDBEditar);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table_refresh.png"))); // NOI18N
        jMenuItem6.setText("Movimentações");
        menuCDB.add(jMenuItem6);

        jMenuBar1.add(menuCDB);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coins.png"))); // NOI18N
        jMenu4.setText("Fundos");

        menuFundosEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/table_edit.png"))); // NOI18N
        menuFundosEditar.setText("Consultar / Editar");
        menuFundosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFundosEditarActionPerformed(evt);
            }
        });
        jMenu4.add(menuFundosEditar);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMenu5.setText("Sobre");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCorrenteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCorrenteEditarActionPerformed
        new TelaConsultarAlterarCorrente().setVisible(true);
    }//GEN-LAST:event_menuCorrenteEditarActionPerformed

    private void menuPoupancaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPoupancaAlterarActionPerformed
        new TelaConsultarAlterarPoupanca().setVisible(true);
    }//GEN-LAST:event_menuPoupancaAlterarActionPerformed

    private void menuClientesEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesEditarActionPerformed
        new TelaEditarClientes().setVisible(true);
    }//GEN-LAST:event_menuClientesEditarActionPerformed

    private void menuCDBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCDBEditarActionPerformed
        new TelaCDBConsultarEditar().setVisible(true);
    }//GEN-LAST:event_menuCDBEditarActionPerformed

    private void menuFundosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFundosEditarActionPerformed
        new TelaFundoConsultarEditar().setVisible(true);
    }//GEN-LAST:event_menuFundosEditarActionPerformed

    private void menuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSairActionPerformed
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_menuArquivoSairActionPerformed

    private void menuCCMovimentacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCCMovimentacoesActionPerformed
        new TelaMovimentacoes().setVisible(true);
    }//GEN-LAST:event_menuCCMovimentacoesActionPerformed

    private void menuCPConsultarDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCPConsultarDepositosActionPerformed
        new TelaConsultarDepositos().setVisible(true);
    }//GEN-LAST:event_menuCPConsultarDepositosActionPerformed

    private void menuAvancaTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAvancaTempoActionPerformed
        long dias = Long.parseLong(JOptionPane.showInputDialog("Quantidade de dias: "));
        calendario.setData(dias);

        this.setTitle("Banco de investimentos -  " + logado.getLogado().getNome() + " - " + calendario.getDataFormatada());
        System.out.println("Data antes de verificar se paga: " + calendario.getDataFormatada());
        taxas.verificaSePaga(calendario.getData());
        

    }//GEN-LAST:event_menuAvancaTempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenuItem menuAvancaTempo;
    private javax.swing.JMenuItem menuCCMovimentacoes;
    private javax.swing.JMenu menuCDB;
    private javax.swing.JMenuItem menuCDBEditar;
    private javax.swing.JMenuItem menuCPConsultarDepositos;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuClientesEditar;
    private javax.swing.JMenu menuCorrente;
    private javax.swing.JMenuItem menuCorrenteEditar;
    private javax.swing.JMenuItem menuFundosEditar;
    private javax.swing.JMenu menuPoupanca;
    private javax.swing.JMenuItem menuPoupancaAlterar;
    // End of variables declaration//GEN-END:variables
}
