/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import mvc.model.Calendario;

/**
 *
 * @author leonardo
 */
public class TelaPrincipalADM extends javax.swing.JFrame {
    Calendario calendario = new Calendario();

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalADM() {
        initComponents();
        
        
    }
    
    //Lembrar de remover 
    public static void main(String[] args) {
        new  TelaPrincipalADM().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataAtual = new javax.swing.JLabel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuArquivoSair = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuClientesEditar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        menuContasCorrenteEditar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuContasPoupancaEditar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuCDB = new javax.swing.JMenu();
        menuCDBEditar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuFundos = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco de Investimentos - Tela Principal");
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        DataAtual.setText(calendario.getDataFormatada().toString());

        jDesktopPane.setAutoscrolls(true);
        jDesktopPane.setMinimumSize(new java.awt.Dimension(800, 445));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/page_white_text.png"))); // NOI18N
        jMenu1.setText("Arquivo");

        menuArquivoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/disconnect.png"))); // NOI18N
        menuArquivoSair.setText("Sair");
        menuArquivoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArquivoSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuArquivoSair);

        jMenuBar1.add(jMenu1);

        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group_edit.png"))); // NOI18N
        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });

        menuClientesEditar.setText("Consultar/Editar");
        menuClientesEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesEditarActionPerformed(evt);
            }
        });
        menuClientes.add(menuClientesEditar);

        jMenuBar1.add(menuClientes);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog_edit.png"))); // NOI18N
        jMenu5.setText("Contas");
        jMenu5.add(jSeparator1);

        jMenu2.setText("Corrente");

        menuContasCorrenteEditar.setText("Editar");
        menuContasCorrenteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasCorrenteEditarActionPerformed(evt);
            }
        });
        jMenu2.add(menuContasCorrenteEditar);

        jMenuItem2.setText("Consultar extrato");
        jMenu2.add(jMenuItem2);

        jMenu5.add(jMenu2);

        jMenu4.setText("Poupança");

        menuContasPoupancaEditar.setText("Editar");
        menuContasPoupancaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContasPoupancaEditarActionPerformed(evt);
            }
        });
        jMenu4.add(menuContasPoupancaEditar);

        jMenuItem4.setText("Consultar extrato");
        jMenu4.add(jMenuItem4);

        jMenu5.add(jMenu4);

        jMenuBar1.add(jMenu5);

        menuCDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog_edit.png"))); // NOI18N
        menuCDB.setText("CDB");

        menuCDBEditar.setText("Editar");
        menuCDBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCDBEditarActionPerformed(evt);
            }
        });
        menuCDB.add(menuCDBEditar);

        jMenuItem3.setText("Consultar extrato");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuCDB.add(jMenuItem3);

        jMenuBar1.add(menuCDB);

        menuFundos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cog_edit.png"))); // NOI18N
        menuFundos.setText("Fundos");

        jMenuItem5.setText("Editar");
        menuFundos.add(jMenuItem5);

        jMenuItem6.setText("Consultar extrato");
        menuFundos.add(jMenuItem6);

        jMenuBar1.add(menuFundos);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jMenu3.setText("Sobre");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DataAtual)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataAtual)
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuClientesEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesEditarActionPerformed
        TelaADMClientes telaClientes = new TelaADMClientes();
        
        jDesktopPane.add(telaClientes);
        telaClientes.setVisible(true);
    }//GEN-LAST:event_menuClientesEditarActionPerformed

    private void menuCDBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCDBEditarActionPerformed
        TelaADMCDB telaCDB = new TelaADMCDB();
        jDesktopPane.add(telaCDB);
        telaCDB.setVisible(true);
    }//GEN-LAST:event_menuCDBEditarActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaADMCDBExtrato telaCDBExtrato = new TelaADMCDBExtrato();
        jDesktopPane.add(telaCDBExtrato);
        telaCDBExtrato.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuContasCorrenteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasCorrenteEditarActionPerformed
        TelaADMCC telaCCEditar = new TelaADMCC();
        jDesktopPane.add(telaCCEditar);
        telaCCEditar.setVisible(true);
    }//GEN-LAST:event_menuContasCorrenteEditarActionPerformed

    private void menuContasPoupancaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContasPoupancaEditarActionPerformed
        TelaADMCP telaCPEditar = new TelaADMCP();
        jDesktopPane.add(telaCPEditar);
        telaCPEditar.setVisible(true);
    }//GEN-LAST:event_menuContasPoupancaEditarActionPerformed

    private void menuArquivoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArquivoSairActionPerformed
        this.dispose();
        new TelaLogin().setVisible(true);
    }//GEN-LAST:event_menuArquivoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DataAtual;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuArquivoSair;
    private javax.swing.JMenu menuCDB;
    private javax.swing.JMenuItem menuCDBEditar;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuClientesEditar;
    private javax.swing.JMenuItem menuContasCorrenteEditar;
    private javax.swing.JMenuItem menuContasPoupancaEditar;
    private javax.swing.JMenu menuFundos;
    // End of variables declaration//GEN-END:variables
}
